server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://db:5432/shareit
    username: dbuser
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate: ddl-auto=none
    properties:
      hibernate: format_sql=true
  sql:
    init: mode=always
